import { Geist, Geist_Mono , DM_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const dm = DM_Sans({
  subsets: ["latin"], // Load only necessary characters
  weight: ["400", "500", "700"], // Specify weights
  variable: "--font-dm-sans", // CSS variable for styling
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dm.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
